name: CMake

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win64
          - win32
        include:
          - name: win64
            os: windows-latest
            cmake_opts: -A x64
          - name: win32
            os: windows-latest
            cmake_opts: -A Win32
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      run: |
        mkdir build
    - name: Build
      run: |
        cmake .. ${{ matrix.cmake_opts }}
        cmake --build . --config Release
      working-directory: ./build
    - name: Package
      run: |
        cmake --build . --config Release --target package
        cmake -E remove_directory ./pkg/_CPack_Packages
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: build/pkg
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download win64
        uses: actions/download-artifact@v4
        with:
          name: win64
          path: pkg
      - name: Download win32
        uses: actions/download-artifact@v4
        with:
          name: win32
          path: pkg
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "pkg/*"
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
